if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 13
ZOXIDE_CMD_OVERRIDE=cd
plugins=(git fzf zoxide mise common-aliases cp docker uv)
# zsh-you-should-use zsh-autosuggestions
source $ZSH/oh-my-zsh.sh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Environment
export RIPGREP_CONFIG_PATH=~/.config/ripgreprc
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR=vim
else
  export EDITOR='code --wait'
fi

# PATH
export PATH=~/pr/github/divadvo-scripts:~/.local/bin:$PATH

# Functions
function chpwd_ls { ls }
add-zsh-hook chpwd chpwd_ls
